const API_URL =
  typeof window === 'undefined'
    ? (process.env['API_URL'] ?? 'http://localhost:4000')       // server-side (container)
    : (process.env['NEXT_PUBLIC_API_URL'] ?? 'http://localhost:4000'); // browser

/**
 * UUID — RFC-4122 v4 identifier generated by Postgres gen_random_uuid().
 * Represented as a string in TypeScript/JavaScript.
 */
export type UUID = string;

export interface User {
  id: UUID;
  email: string;
  name: string | null;
  provider: string;
  is_admin: boolean;
}

export interface Need {
  id: UUID;
  title: string;
  description: string | null;
  status: string;
  is_public: boolean;
  quantity: number;
  needed_by: string | null;
  owner_id: UUID | null;
  created_at: string;
  updated_at: string;
}

export interface Resource {
  id: UUID;
  title: string;
  description: string | null;
  status: string;
  is_public: boolean;
  quantity: number;
  available_until: string | null;
  owner_id: UUID | null;
  created_at: string;
  updated_at: string;
  photo?: ResourcePhotoAttachment | null;
}

export interface ResourcePhotoBoundingBox {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface ResourcePhotoDetection {
  label: string;
  confidence: number;
  box: ResourcePhotoBoundingBox;
}

export interface ResourcePhotoAttachment {
  mimeType: string;
  imageBase64: string;
  width: number;
  height: number;
  focusBox: ResourcePhotoBoundingBox | null;
  detections: ResourcePhotoDetection[];
}

export interface NeedImportDraft {
  title: string;
  description: string | null;
  quantity: number;
  status: 'open' | 'fulfilled' | 'closed';
  is_public: boolean;
  needed_by: string | null;
}

export interface ResourceImportDraft {
  title: string;
  description: string | null;
  quantity: number;
  status: 'available' | 'allocated' | 'retired';
  is_public: boolean;
  available_until: string | null;
  photo?: ResourcePhotoAttachment;
}

export type PhotoImportReasonCode =
  | 'UNSUPPORTED_MIME'
  | 'FILE_TOO_LARGE'
  | 'DIMENSIONS_TOO_SMALL'
  | 'MODERATION_UNSAFE'
  | 'MODERATION_AMBIGUOUS'
  | 'TEXT_POLICY_VIOLATION'
  | 'NOT_A_RESOURCE_IMAGE'
  | 'INTERNAL_ERROR';

export interface PhotoImportDiagnostics {
  provider: 'claude' | 'stub';
  model: string;
  usedVision: boolean;
  latencyMs: number;
  moderationVerdict: 'safe' | 'unsafe' | 'ambiguous';
  relevanceVerdict: 'resource' | 'not_resource';
  extractedTextPreview: string;
  detectionsCount?: number;
}

export type ResourcePhotoPreviewResponse =
  | {
      status: 'allow';
      draft: ResourceImportDraft & { evidence_status: 'photo_attached' };
      additionalDrafts?: Array<ResourceImportDraft & { evidence_status: 'photo_attached' }>;
      diagnostics?: PhotoImportDiagnostics;
    }
  | {
      status: 'reject';
      code: PhotoImportReasonCode;
      message: string;
      diagnostics?: PhotoImportDiagnostics;
    };

export interface ImportPreviewResponse<T> {
  items: T[];
  estimatedTokens: number;
  inputTokenLimit: number;
  inputMaxChars: number;
}

export interface Match {
  id: UUID;
  need_id: UUID;
  resource_id: UUID;
  score: number;
  rationale: string | null;
  strategy: string;
  matched_at: string;
  need_title: string;
  need_status: string;
  need_owner_id: UUID | null;
  resource_title: string;
  resource_status: string;
  resource_owner_id: UUID | null;
  seen_at: string | null;
}

async function apiFetch<T>(
  path: string,
  options: RequestInit = {}
): Promise<T> {
  const res = await fetch(`${API_URL}${path}`, {
    ...options,
    credentials: 'include',
    headers: { 'Content-Type': 'application/json', ...options.headers },
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({ error: res.statusText }));
    throw new Error((err as { error?: string }).error ?? res.statusText);
  }
  return res.json() as Promise<T>;
}

// ── Auth ──────────────────────────────────────────────────────
export const getMe = () => apiFetch<User>('/auth/me');
export const login = () => apiFetch<User>('/auth/login', { method: 'POST' });
export const logout = () => apiFetch<{ ok: boolean }>('/auth/logout', { method: 'POST' });

// ── Needs ─────────────────────────────────────────────────────
export const listNeeds = () => apiFetch<Need[]>('/api/needs');
export const getOnNeed = (id: string) => apiFetch<Need>(`/api/needs/${id}`);
export const createNeed = (body: { title: string; description?: string; is_public?: boolean; quantity?: number; needed_by?: string }) =>
  apiFetch<Need>('/api/needs', { method: 'POST', body: JSON.stringify(body) });
export const updateNeed = (
  id: string,
  body: { title?: string; description?: string; status?: string; is_public?: boolean; quantity?: number; needed_by?: string | null }
) => apiFetch<Need>(`/api/needs/${id}`, { method: 'PUT', body: JSON.stringify(body) });
export const deleteNeed = (id: string) =>
  apiFetch<{ ok: boolean }>(`/api/needs/${id}`, { method: 'DELETE' });
export const searchNeeds = (q: string) =>
  apiFetch<Need[]>(`/api/needs/search?q=${encodeURIComponent(q)}`);
export const previewNeedImport = (text: string) =>
  apiFetch<ImportPreviewResponse<NeedImportDraft>>('/api/needs/import/preview', {
    method: 'POST',
    body: JSON.stringify({ text }),
  });
export const commitNeedImport = (items: NeedImportDraft[]) =>
  apiFetch<Need[]>('/api/needs/import/commit', {
    method: 'POST',
    body: JSON.stringify({ items }),
  });

// ── Resources ─────────────────────────────────────────────────
export const listResources = () => apiFetch<Resource[]>('/api/resources');
export const getOneResource = (id: string) => apiFetch<Resource>(`/api/resources/${id}`);
export const createResource = (body: { title: string; description?: string; is_public?: boolean; quantity?: number; available_until?: string }) =>
  apiFetch<Resource>('/api/resources', { method: 'POST', body: JSON.stringify(body) });
export const updateResource = (
  id: string,
  body: { title?: string; description?: string; status?: string; is_public?: boolean; quantity?: number; available_until?: string | null }
) => apiFetch<Resource>(`/api/resources/${id}`, { method: 'PUT', body: JSON.stringify(body) });
export const deleteResource = (id: string) =>
  apiFetch<{ ok: boolean }>(`/api/resources/${id}`, { method: 'DELETE' });
export const searchResources = (q: string) =>
  apiFetch<Resource[]>(`/api/resources/search?q=${encodeURIComponent(q)}`);
export const previewResourceImport = (text: string) =>
  apiFetch<ImportPreviewResponse<ResourceImportDraft>>('/api/resources/import/preview', {
    method: 'POST',
    body: JSON.stringify({ text }),
  });
export const commitResourceImport = (items: ResourceImportDraft[]) =>
  apiFetch<Resource[]>('/api/resources/import/commit', {
    method: 'POST',
    body: JSON.stringify({ items }),
  });
export const previewResourcePhotoImport = async (photo: File): Promise<ResourcePhotoPreviewResponse> => {
  const form = new FormData();
  form.append('photo', photo);

  const res = await fetch(`${API_URL}/api/resources/import/photo/preview`, {
    method: 'POST',
    credentials: 'include',
    body: form,
  });

  const payload = await res.json().catch(() => ({ error: res.statusText }));
  if (!res.ok && (payload?.status !== 'reject')) {
    throw new Error((payload as { error?: string }).error ?? res.statusText);
  }
  return payload as ResourcePhotoPreviewResponse;
};

// ── Matches ───────────────────────────────────────────────────
export const listMatches = (filters?: { needId?: string; resourceId?: string; unseenOnly?: boolean }) => {
  const params = new URLSearchParams();
  if (filters?.needId) params.set('needId', filters.needId);
  if (filters?.resourceId) params.set('resourceId', filters.resourceId);
  if (filters?.unseenOnly) params.set('unseenOnly', 'true');
  const suffix = params.toString();
  return apiFetch<Match[]>(`/api/matches${suffix ? `?${suffix}` : ''}`);
};

export const getUnseenMatchesCount = () =>
  apiFetch<{ count: number }>('/api/matches/unseen-count');

export const markMatchesSeen = (matchIds: string[]) =>
  apiFetch<{ ok: boolean; marked: number }>('/api/matches/seen', {
    method: 'POST',
    body: JSON.stringify({ matchIds }),
  });

// ── Admin ─────────────────────────────────────────────────────
export interface RematchStats {
  ok: boolean;
  strategy: string;
  needsScanned: number;
  resourcesScanned: number;
  matchesUpserted: number;
  durationMs: number;
  error?: string;
}

export const triggerFullRematch = () =>
  apiFetch<RematchStats>('/admin/rematch/full', { method: 'POST' });

export const triggerPartialRematch = (since?: string) =>
  apiFetch<RematchStats>('/admin/rematch/partial', {
    method: 'POST',
    body: JSON.stringify(since ? { since } : {}),
  });
