/**
 * UUID is a standard RFC-4122 v4 identifier string (e.g. "550e8400-e29b-41d4-a716-446655440000").
 * Every aggregate-root entity (User, Need, Resource) uses a UUID primary key generated by
 * Postgres's built-in gen_random_uuid(), guaranteeing global uniqueness without coordination.
 */
export type UUID = string;
